### ISSUE TITLE
livemedia-creator stalled during install of libevent

### ISSUE THREAD

**Issue by ycollet** [weldr/lorax#1100]
I use lorax from master repo, but I had the same result with lorax from fedora 32.
Install is stalled during install of libevent. I waited for half a day and nothing change.
The command I used to generate the iso file:
```
# livemedia-creator --make-iso --ks fedora-32-live-jam-xfce.ks --project Audinux --iso-name livecd-fedora-32-mao.iso --iso-only --releasever 32 --volid Audinux --image-name Audinux --resultdir /var/lmc --no-virt --tmp /var/tmp
2020-12-06 09:38:46,687: livemedia-creator v34.5-1
2020-12-06 09:38:46,687: selinux is enabled and in Permissive mode
2020-12-06 09:38:46,850: disk_img = /var/lmc/Audinux
2020-12-06 09:38:46,850: Using disk size of 16386MiB
2020-12-06 09:38:48,317: Running anaconda.
2020-12-06 09:38:54,104: Starting installer, one moment...
2020-12-06 09:38:54,104: terminal size detection failed, using default width
2020-12-06 09:38:54,104: anaconda 32.24.7-2.fc32 for Audinux 32 (pre-release) started.
2020-12-06 09:38:54,105: 09:38:54 Not asking for VNC because of an automated install
2020-12-06 09:38:54,255: Processing logs from ('127.0.0.1', 47782)
2020-12-06 09:40:07,564: Début de l’installation automatique
```
The debug message in livemedia.log:
```
2020-12-06 09:38:46,686 DEBUG livemedia-creator: Namespace(anaconda_args=None, app_file='appliance.xml', app_name=None, app_template=None, arch=None, armplatform=None, compress_args=[], compression='xz', disk_image=None, domacboot=True, dracut_args=None, dracut_conf=None, extra_boot_args='', fs_image=None, fs_label='Anaconda', image_name='Audinux', image_only=False, image_size_align=0, image_type=None, iso=None, iso_name='livecd-fedora-32-mao.iso', iso_only=True, keep_image=False, kernel_args=None, ks=['/home/collette/repositories/github/fedora-spec/kickstart/fedora-32-live-jam-xfce.ks'], live_rootfs_keep_size=False, live_rootfs_size=0, location=None, logfile='/home/collette/repositories/github/fedora-spec/kickstart/livemedia.log', lorax_templates=None, make_ami=False, make_appliance=False, make_disk=False, make_fsimage=False, make_iso=True, make_oci=False, make_ostree_live=False, make_pxe_live=False, make_tar=False, make_tar_disk=False, make_vagrant=False, no_kvm=False, no_virt=True, oci_config=None, oci_runtime=None, ovmf_path='/usr/share/edk2/ovmf/', project='Audinux', proxy=None, qcow2=False, qemu_args=[], ram=2048, releasever='32', result_dir='/var/lmc', squashfs_only=False, tar_disk_name=None, timeout=None, tmp='/var/tmp', vagrant_metadata=None, vagrantfile=None, vcpus=None, virt_uefi=False, vnc=None, volid='Audinux', with_rng='/dev/random')
```

**Comment by bcl** [comment]
This sounds like the same kind of thing as https://bugzilla.redhat.com/show_bug.cgi?id=1900596
Could you attach the logs to that bug, I'm especially interested in `livemedia.log` to see if there is something that can be added to the log monitor. Ideally Anaconda would exit when it hits an error, but that doesn't always happen.

**Comment by ycollet** [comment]
You were right. It's an anaconda problem. Here is a part of /tmp/anaconda.log:
```
21:55:53,003 INF installation: Top-level task queue: Complete installation queue
Number of task queues: 15
Number of tasks: 39
Task & task group listing:
 Task queue: Installation queue
  Task queue: Installation environment setup
   Task: Setup addons
   Task: Configure the runtime system
  Task queue: Early storage configuration
   Task: Activate filesystems
   Task: Mount filesystems
   Task: Write the storage configuration
  Task queue: Pre-install scripts
   Task: Run %pre-install scripts
  Task queue: Pre install tasks
   Task: Configure NTP service enablement
   Task: Discover information about a realm
   Task: Find additional packages & run pre_install()
  Task queue: Payload installation
   Task: Install the payload
  Task queue: Bootloader installation
   Task: Configure the bootloader
   Task: Install the bootloader
  Task queue: Post-installation setup tasks
   Task: Run post-installation setup tasks
 Task queue: Configuration queue
  Task queue: Installed system configuration
   Task: Configure SELinux
   Task: Configure fingerprint authentication
   Task: Authselect configuration
   Task: Authconfig configuration
   Task: Configure Initial Setup
   Task: Configure post-installation tools
   Task: Configure services
   Task: Configure systemd default target
   Task: Configure default desktop
   Task: Configure time zone
   Task: Configure NTP
   Task: Configure language
   Task: Configure keyboard
   Task: Configure firewall
   Task: Create groups
   Task: Create users
   Task: Configure root password
   Task: Set SSH keys
   Task: Configure optional root password SSH login
  Task queue: User creation
  Task queue: Anaconda addon configuration
   Task: Configure Anaconda addons
   Task: Install the system
  Task queue: Initramfs generation
   Task: Generate initramfs
   Task: Rerun zipl
  Task: Join a realm
  Task queue: Post installation scripts
   Task: Run post installation scripts
  Task queue: Write configs and kickstarts
   Task: Store kickstarts
21:55:53,004 INF installation: Queue started: Installation queue (1/15)
21:55:53,004 INF progress: Setting up the installation environment
21:55:53,004 INF installation: Queue started: Installation environment setup (2/15)
21:55:53,005 INF installation: Task started: Setup addons (1/39)
21:55:53,005 INF progress: Setting up com_redhat_kdump addon
21:55:53,005 INF progress: Setup addons
21:55:53,005 DBG installation: Task completed: Setup addons (1/39) (0.0 s)
21:55:53,005 INF installation: Task started: Configure the runtime system (2/39)
21:55:53,014 INF progress: Configure the runtime system
21:55:53,014 DBG installation: Task completed: Configure the runtime system (2/39) (0.0 s)
21:55:53,015 INF progress: Configuring storage
21:55:53,015 INF installation: Queue started: Early storage configuration (3/15)
21:55:53,015 INF installation: Task started: Activate filesystems (3/39)
21:55:53,019 INF progress: Activate filesystems
21:55:53,019 DBG installation: Task completed: Activate filesystems (3/39) (0.0 s)
21:55:53,019 INF installation: Task started: Mount filesystems (4/39)
21:55:56,032 INF progress: Mount filesystems
21:55:56,032 DBG installation: Task completed: Mount filesystems (4/39) (3.0 s)
21:55:56,032 INF installation: Task started: Write the storage configuration (5/39)
21:55:56,036 INF progress: Write the storage configuration
21:55:56,037 DBG installation: Task completed: Write the storage configuration (5/39) (0.0 s)
21:55:56,037 INF progress: Running pre-installation scripts
21:55:56,038 INF installation: Queue started: Pre-install scripts (4/15)
21:55:56,038 INF installation: Task started: Run %pre-install scripts (6/39)
21:55:56,038 INF progress: Run %pre-install scripts
21:55:56,038 DBG installation: Task completed: Run %pre-install scripts (6/39) (0.0 s)
21:55:56,039 INF progress: Running pre-installation tasks
21:55:56,039 INF installation: Queue started: Pre install tasks (5/15)
21:55:56,040 INF installation: Task started: Configure NTP service enablement (7/39)
21:55:57,049 INF progress: Configure NTP service enablement
21:55:57,049 DBG installation: Task completed: Configure NTP service enablement (7/39) (1.0 s)
21:55:57,050 INF installation: Task started: Discover information about a realm (8/39)
21:55:57,057 INF progress: Discover information about a realm
21:55:57,057 DBG installation: Task completed: Discover information about a realm (8/39) (0.0 s)
21:55:57,057 INF installation: Task started: Find additional packages & run pre_install() (9/39)
21:55:57,064 DBG payload.requirement: no group requirement added for language groups
21:56:02,694 DBG payload.requirement: added package requirement 'langpacks-fr' for langpacks, strong=False
21:56:02,698 DBG installation: Adding requirements for module org.fedoraproject.Anaconda.Modules.Security : [Requirement(name='authselect-compat', reason='Needed to support legacy authconfig kickstart command.', type='package')]
21:56:02,698 DBG payload.requirement: added package requirement 'authselect-compat' for Needed to support legacy authconfig kickstart command., strong=True
21:56:02,760 DBG installation: Adding requirements for module org.fedoraproject.Anaconda.Modules.Network : [Requirement(name='firewalld', reason='Requested by the firewall kickstart command.', type='package')]
21:56:02,760 DBG payload.requirement: added package requirement 'firewalld' for Requested by the firewall kickstart command., strong=True
21:56:02,765 DBG installation: Adding requirements for module org.fedoraproject.Anaconda.Modules.Timezone : [Requirement(name='chrony', reason='Needed to run NTP service.', type='package')]
21:56:02,765 DBG payload.requirement: added package requirement 'chrony' for Needed to run NTP service., strong=True
21:56:02,768 DBG installation: Adding requirements for module org.fedoraproject.Anaconda.Modules.Storage : []
21:56:02,834 INF progress: Find additional packages & run pre_install()
21:56:02,834 DBG installation: Task completed: Find additional packages & run pre_install() (9/39) (5.8 s)
21:56:02,836 INF progress: Installing.
21:56:02,836 INF installation: Queue started: Payload installation (6/15)
21:56:02,836 INF installation: Task started: Install the payload (10/39)
21:56:02,837 INF progress: Starting package installation process
21:56:02,934 DBG payload.requirement: apply with result True called on requirements [('package', 'langpacks-fr', PayloadRequirement(id=langpacks-fr, reasons=[PayloadRequirementReason(reason='langpacks', strong=False)])), ('package', 'authselect-compat', PayloadRequirement(id=authselect-compat, reasons=[PayloadRequirementReason(reason='Needed to support legacy authconfig kickstart command.', strong=True)])), ('package', 'firewalld', PayloadRequirement(id=firewalld, reasons=[PayloadRequirementReason(reason='Requested by the firewall kickstart command.', strong=True)])), ('package', 'chrony', PayloadRequirement(id=chrony, reasons=[PayloadRequirementReason(reason='Needed to run NTP service.', strong=True)]))]
22:04:43,402 INF progress: Preparing transaction from installation source
22:13:42,720 INF threading: Thread Failed: AnaInstallThread (140358612465408)
22:13:42,720 DBG exception: running handleException
22:13:42,812 CRT exception: Traceback (most recent call last):

  File "/usr/lib64/python3.8/site-packages/pyanaconda/threading.py", line 280, in run
    threading.Thread.run(self)

  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)

  File "/usr/lib64/python3.8/site-packages/pyanaconda/installation.py", line 382, in run_installation
    queue.start()

  File "/usr/lib64/python3.8/site-packages/pyanaconda/installation_tasks.py", line 311, in start
    item.start()

  File "/usr/lib64/python3.8/site-packages/pyanaconda/installation_tasks.py", line 311, in start
    item.start()

  File "/usr/lib64/python3.8/site-packages/pyanaconda/installation_tasks.py", line 311, in start
    item.start()

  File "/usr/lib64/python3.8/site-packages/pyanaconda/installation_tasks.py", line 490, in start
    self.run_task()

  File "/usr/lib64/python3.8/site-packages/pyanaconda/installation_tasks.py", line 456, in run_task
    self._task(*self._task_args, **self._task_kwargs)

  File "/usr/lib64/python3.8/site-packages/pyanaconda/payload/dnfpayload.py", line 1084, in install
    if errors.errorHandler.cb(exc) == errors.ERROR_RAISE:

  File "/usr/lib64/python3.8/site-packages/pyanaconda/errors.py", line 279, in cb
    raise NonInteractiveError("Non interactive installation failed: %s" % exn)

pyanaconda.errors.NonInteractiveError: Non interactive installation failed: DNF error: Error in POSTIN scriptlet in rpm package selinux-policy-targeted

22:13:43,382 DBG exception: Gtk not running, starting Gtk and running exception handler in it
22:13:43,383 INF threading: Thread Done: AnaInstallThread (140358612465408)
```

**Comment by bcl** [comment]
See #1101 and see if it helps.
