### ISSUE TITLE
CentOS8.5.2111 `--excludepkgs anaconda-install-img-deps` failed

### ISSUE THREAD

**Issue by Rtoax** [weldr/lorax#1247]
`centos 8.5.2111` don't have `anaconda-install-img-deps` rpm, so i just add `--excludepkgs anaconda-install-img-deps` to `lorax` command line, but it's still not work for me.

```
2022-07-05 05:17:35,145: installing runtime packages
installing runtime packages
2022-07-05 05:17:35,161: running runtime-install.tmpl
running runtime-install.tmpl
2022-07-05 05:17:35,165: installpkg anaconda-install-img-deps failed: no package matched: anaconda-install-img-deps
installpkg anaconda-install-img-deps failed: no package matched: anaconda-install-img-deps
2022-07-05 05:17:35,165: template command error in runtime-install.tmpl:
template command error in runtime-install.tmpl:
2022-07-05 05:17:35,165:   installpkg anaconda anaconda-widgets kexec-tools-anaconda-addon anaconda-install-img-deps
  installpkg anaconda anaconda-widgets kexec-tools-anaconda-addon anaconda-install-img-deps
2022-07-05 05:17:35,165:   Exception: Required installpkg failed.
  Exception: Required installpkg failed.
Traceback (most recent call last):
  File "/sbin/lorax", line 226, in <module>
    main()
  File "/sbin/lorax", line 207, in main
    lorax.run(dnfbase, opts.product, opts.version, opts.release,
  File "/usr/lib/python3.9/site-packages/pylorax/__init__.py", line 271, in run
    rb.install()
  File "/usr/lib/python3.9/site-packages/pylorax/treebuilder.py", line 145, in install
    self._runner.run("runtime-install.tmpl")
  File "/usr/lib/python3.9/site-packages/pylorax/ltmpl.py", line 149, in run
    self._run(commands)
  File "/usr/lib/python3.9/site-packages/pylorax/ltmpl.py", line 168, in _run
    f(*args)
  File "/usr/lib/python3.9/site-packages/pylorax/ltmpl.py", line 603, in installpkg
    raise Exception("Required installpkg failed.")
Exception: Required installpkg failed.
```

**Comment by Rtoax** [comment]
After i swap to use `centos 8.5.2111` host to execute `lorax`, this problem solved.
