### ISSUE TITLE
aarch64:  The rootfs ran out of space with size=2

### ISSUE THREAD

**Issue by T0MASD** [weldr/lorax#1378]
I'm trying to run lorax on aarch64 in mock:
```
Namespace(
  (product = "Fedora"),
  (version = "38"),
  (release = "38"),
  (source = [
    "http://download.fedoraproject.org/pub/fedora/linux/releases/38/Everything/aarch64/os/",
  ]),
  (repos = ["/build/dnf.repo"]),
  (mirrorlist = []),
  (variant = ""),
  (bugurl = "your distribution provided bug reporting tool"),
  (isfinal = False),
  (config = "/etc/lorax/lorax.conf"),
  (proxy = None),
  (installpkgs = ["util-linux", "parted", "wireguard-tools"]),
  (excludepkgs = []),
  (buildarch = None),
  (volid = None),
  (domacboot = False),
  (doupgrade = True),
  (logfile = "/build/lorax.log"),
  (tmp = "/var/tmp/lorax"),
  (cachedir = None),
  (workdir = None),
  (force = False),
  (add_templates = []),
  (add_template_vars = []),
  (add_arch_templates = []),
  (add_arch_template_vars = []),
  (verify = True),
  (sharedir = None),
  (enablerepos = []),
  (disablerepos = []),
  (rootfs_size = 2),
  (noverifyssl = False),
  (dnfplugins = []),
  (squashfs_only = False),
  (skip_branding = False),
  (dracut_conf = None),
  (dracut_args = None),
  (outputdir = "/build/results"),
);
...
    2024-02-07 22:03:48,917: running runtime-postinstall.tmpl
    running runtime-postinstall.tmpl
    2024-02-07 22:03:50,395: writing .discinfo file
    writing .discinfo file
    2024-02-07 22:03:50,397: backing up installroot
    backing up installroot
    2024-02-07 22:03:51,585: generating kernel module metadata
    generating kernel module metadata
    2024-02-07 22:03:51,587: doing depmod and module-info for 6.7.3-100.fc38.aarch64
    doing depmod and module-info for 6.7.3-100.fc38.aarch64
    2024-02-07 22:04:01,333: cleaning unneeded files
    cleaning unneeded files
    2024-02-07 22:04:01,360: running runtime-cleanup.tmpl
    running runtime-cleanup.tmpl
    2024-02-07 22:04:04,015: verifying the installroot
    verifying the installroot
    2024-02-07 22:04:08,998: creating the runtime image
    creating the runtime image
    2024-02-07 22:04:08,999: no BCJ filter for arch aarch64
    no BCJ filter for arch aarch64
    2024-02-07 22:04:44,312: The rootfs ran out of space with size=2
    The rootfs ran out of space with size=2
    Traceback (most recent call last):
      File "/usr/sbin/lorax", line 223, in <module>
        main()
      File "/usr/sbin/lorax", line 204, in main
        lorax.run(dnfbase, opts.product, opts.version, opts.release,
      File "/usr/lib/python3.11/site-packages/pylorax/__init__.py", line 325, in run
        rc = rb.create_ext4_runtime(joinpaths(installroot,runtime),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/pylorax/treebuilder.py", line 254, in create_ext4_runtime
        imgutils.mkrootfsimg(self.vars.root, joinpaths(workdir, "LiveOS/rootfs.img"),
      File "/usr/lib/python3.11/site-packages/pylorax/imgutils.py", line 136, in mkrootfsimg
        mkext4img(rootdir, outfile, label=label, size=fssize)
      File "/usr/lib/python3.11/site-packages/pylorax/imgutils.py", line 579, in mkext4img
        mkfsimage("ext4", rootdir, outfile, size, mountargs=mountargs,
      File "/usr/lib/python3.11/site-packages/pylorax/imgutils.py", line 558, in mkfsimage
        copytree(rootdir, mnt, preserve)
      File "/usr/lib/python3.11/site-packages/pylorax/imgutils.py", line 298, in copytree
        runcmd(cp)
      File "/usr/lib/python3.11/site-packages/pylorax/executils.py", line 367, in runcmd
        return execWithRedirect(cmd[0], cmd[1:], **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/pylorax/executils.py", line 230, in execWithRedirect
        return _run_program(argv, stdin=stdin, stdout=stdout, root=root, env_prune=env_prune,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/pylorax/executils.py", line 205, in _run_program
        raise subprocess.CalledProcessError(proc.returncode, argv, output)
    subprocess.CalledProcessError: Command '['cp', '-a', '/var/tmp/lorax/lorax.1jpyxrdy/installtree/.', '/var/tmp/lorax/lorax.imgutils.rj1ktug_']' returned non-zero exit status 1.
    2024-02-07 22:04:44,324: Cleaning up tempdir - /var/tmp/lorax/lorax.1jpyxrdy
  stdout_lines: <omitted>
```

I tried  adding size=5 in https://github.com/weldr/lorax/blob/master/src/pylorax/treebuilder.py#L245 but I it didn't have any affect.

my system has enough space:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        4.0M     0  4.0M   0% /dev
tmpfs           913M     0  913M   0% /dev/shm
tmpfs           366M  500K  365M   1% /run
/dev/nvme0n1p3   28G   11G   17G  39% /
tmpfs           913M     0  913M   0% /tmp
/dev/nvme0n1p2  974M   75M  832M   9% /boot
/dev/nvme0n1p1  599M  7.3M  592M   2% /boot/efi
tmpfs           183M  4.0K  183M   1% /run/user/1000
```

**Comment by T0MASD** [comment]
Added `--rootfs-size=5` to lorax command and it worked!
