### ISSUE TITLE
/dev/null: Permission denied with --old-chroot

### ISSUE THREAD

**Issue by boydkelly** [weldr/lorax#340]
I have tried to follow exactly the instructions here to create a live cd (on Fedora Rawhide).  
https://fedoraproject.org/wiki/Livemedia-creator-_How_to_create_and_use_a_Live_CD

When I try to enter the mock chroot with the --old-chroot option I get a repeated message:  /dev/null Ppermission denied.  Without the --old-chroot option I enter the chroot with no error but then cannot build a livecd.  I have selinux to permissive and  seem to have permissions on /dev/null.

[bkelly@y2 ~]$ mock -r fedora-27-x86_64 --shell --old-chroot
INFO: mock.py version 1.4.9 starting (python version = 3.6.4)...
Start: init plugins
INFO: selinux enabled
Finish: init plugins
Start: run
Start: chroot init
INFO: calling preinit hooks
INFO: enabled root cache
INFO: enabled dnf cache
Start: cleaning dnf metadata
Finish: cleaning dnf metadata
INFO: enabled HW Info plugin
Finish: chroot init
Start: shell
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
sh: /dev/null: Permission denied
<mock-chroot> sh-4.4# cd fedora-kickstarts/
<mock-chroot> sh-4.4# livemedia-creator --ks flat-fedora-live-soas.ks --no-virt --resultdir /var/lmc --project Fedora-soas-Live --make-iso --volid Fedora-SoaS-26 --iso-only --iso-name Fedora-SoaS-27-x86_64.iso --releasever 27 --title Fedora-SoaS-live --macboot
/bin/sh: /dev/null: Permission denied
2018-03-20 17:49:54,038: livemedia-creator v27.11-1
2018-03-20 17:49:54,131: disk_img = /var/lmc/lmc-disk-x3e79tst.img
2018-03-20 17:49:54,132: Using disk size of 5122MiB
Traceback (most recent call last):
  File "/usr/sbin/livemedia-creator", line 1478, in <module>
    main()
  File "/usr/sbin/livemedia-creator", line 1395, in main
    disk_img = make_image(opts, ks)
  File "/usr/sbin/livemedia-creator", line 1080, in make_image
    novirt_install(opts, disk_img, disk_size)
  File "/usr/sbin/livemedia-creator", line 747, in novirt_install
    mkext4img(None, disk_img, label=opts.fs_label, size=disk_size * 1024**2)
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 469, in mkext4img
    mkfsargs=["-L", label, "-b", "4096", "-m", "0"], graft=graft)
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 444, in mkfsimage
    with LoopDev(outfile, size) as loopdev:
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 324, in __enter__
    self.loopdev = loop_attach(self.filename)
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 178, in loop_attach
    dev = runcmd_output(["losetup", "--find", "--show", outfile])
  File "/usr/lib/python3.6/site-packages/pylorax/executils.py", line 347, in runcmd_output
    return execWithCapture(cmd[0], cmd[1:], **kwargs)
  File "/usr/lib/python3.6/site-packages/pylorax/executils.py", line 249, in execWithCapture
    reset_handlers=reset_handlers, reset_lang=reset_lang)[1]
  File "/usr/lib/python3.6/site-packages/pylorax/executils.py", line 201, in _run_program
    raise subprocess.CalledProcessError(proc.returncode, argv, output)
subprocess.CalledProcessError: Command '['losetup', '--find', '--show', '/var/lmc/lmc-disk-x3e79tst.img']' returned non-zero exit status 1.
<mock-chroot> sh-4.4# 

If I enter the chroot without --old-chroot then I get the following:

<mock-chroot> sh-4.4# !105
livemedia-creator --ks flat-fedora-live-soas.ks --no-virt --resultdir /var/lmc --project Fedora-soas-Live --make-iso --volid Fedora-SoaS-26 --iso-only --iso-name Fedora-SoaS-27-x86_64.iso --releasever 27 --title Fedora-SoaS-live --macboot
2018-03-20 17:43:00,959: livemedia-creator v27.11-1
2018-03-20 17:43:01,053: disk_img = /var/lmc/lmc-disk-jbq0bsii.img
2018-03-20 17:43:01,054: Using disk size of 5122MiB
Traceback (most recent call last):
  File "/usr/sbin/livemedia-creator", line 1478, in <module>
    main()
  File "/usr/sbin/livemedia-creator", line 1395, in main
    disk_img = make_image(opts, ks)
  File "/usr/sbin/livemedia-creator", line 1080, in make_image
    novirt_install(opts, disk_img, disk_size)
  File "/usr/sbin/livemedia-creator", line 747, in novirt_install
    mkext4img(None, disk_img, label=opts.fs_label, size=disk_size * 1024**2)
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 469, in mkext4img
    mkfsargs=["-L", label, "-b", "4096", "-m", "0"], graft=graft)
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 444, in mkfsimage
    with LoopDev(outfile, size) as loopdev:
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 324, in __enter__
    self.loopdev = loop_attach(self.filename)
  File "/usr/lib/python3.6/site-packages/pylorax/imgutils.py", line 178, in loop_attach
    dev = runcmd_output(["losetup", "--find", "--show", outfile])
  File "/usr/lib/python3.6/site-packages/pylorax/executils.py", line 347, in runcmd_output
    return execWithCapture(cmd[0], cmd[1:], **kwargs)
  File "/usr/lib/python3.6/site-packages/pylorax/executils.py", line 249, in execWithCapture
    reset_handlers=reset_handlers, reset_lang=reset_lang)[1]
  File "/usr/lib/python3.6/site-packages/pylorax/executils.py", line 201, in _run_program
    raise subprocess.CalledProcessError(proc.returncode, argv, output)
subprocess.CalledProcessError: Command '['losetup', '--find', '--show', '/var/lmc/lmc-disk-jbq0bsii.img']' returned non-zero exit status 1.
<mock-chroot> sh-4.4#

**Comment by bcl** [comment]
Sorry, I have no idea what's going on there.It looks like a problem with your mock installation. You might try filing a bug with mock at https://bugzilla.redhat.com
