### ISSUE TITLE
Add checks for losetup race problems

### ISSUE THREAD

**Issue by bcl** [weldr/lorax#369]
Some users are reporting that on rare occasions parallel runs of lorax try to use the same /dev/loopX device is used, causing one of them to fail. Add a retry loop to losetup usage to work around this.

DEBUG util.py:257:  Traceback (most recent call last):
DEBUG util.py:257:    File "/usr/sbin/mkefiboot", line 155, in <module>
DEBUG util.py:257:      mkefiboot(opt.bootdir, opt.outfile, opt.label)
DEBUG util.py:257:    File "/usr/sbin/mkefiboot", line 32, in mkefiboot
DEBUG util.py:257:      mkdosimg(None, outfile, label=label, graft={'EFI/BOOT':bootdir})
DEBUG util.py:257:    File "/usr/lib/python2.7/site-packages/pylorax/imgutils.py", line 412, in mkdosimg
DEBUG util.py:257:      mkfsargs=["-n", label], graft=graft)
DEBUG util.py:257:    File "/usr/lib/python2.7/site-packages/pylorax/imgutils.py", line 393, in mkfsimage
DEBUG util.py:257:      with LoopDev(outfile, size) as loopdev:
DEBUG util.py:257:    File "/usr/lib/python2.7/site-packages/pylorax/imgutils.py", line 298, in __enter__
DEBUG util.py:257:      self.loopdev = loop_attach(self.filename)
DEBUG util.py:257:    File "/usr/lib/python2.7/site-packages/pylorax/imgutils.py", line 158, in loop_attach
DEBUG util.py:257:      loop_waitfor(dev.strip(), outfile)
DEBUG util.py:257:    File "/usr/lib/python2.7/site-packages/pylorax/imgutils.py", line 150, in loop_waitfor
DEBUG util.py:257:      raise RuntimeError("Unable to setup %s on %s" % (loop_dev, outfile))

**Comment by bcl** [comment]
'Fixed' in commit 936d193413375153a671f709371ed8bdd58730de
