### ISSUE TITLE
rhel-livemedia.ks and centos-livemedia.ks

### ISSUE THREAD

**Issue by probonopd** [weldr/lorax#864]
In addition to `fedora-livemedia.ks`, please also add `rhel-livemedia.ks` and `centos-livemedia.ks`.
Use case: I would like to make a RHEL 8 and/or CentOS 8 Live ISO image to evaluate those systems (without needing virtualization or a dedicated hard disk) since there is no one available for download.

Maybe https://pagure.io/fedora-kickstarts/blob/master/f/fedora-live-workstation.ks can be reused.

https://weldr.io/lorax/lorax-composer/livemedia-creator.html talks about RHEL and is citing `./docs/rhel7-livemedia.ks`.

https://pagure.io/fedora-kickstarts/tree/master seems to be the location where ks files live, but only for Fedora and not for RHEL or CentOS.

Reference:
https://github.com/CentOS/sig-core-livemedia/issues/1

**Comment by probonopd** [comment]
Turns out different branches of this repository contain different content, and the __rhel8.0-branch__ does contain https://github.com/weldr/lorax/blob/rhel8.0-branch/docs/rhel-livemedia.ks indeed. it even contains a script to produce what seems to be a RHEL 8 Live ISO: https://github.com/weldr/lorax/blob/rhel8-branch/tests/cli/test_compose_live-iso.sh

**Comment by probonopd** [comment]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/composing_a_customized_rhel_system_image/composer-description_composing-a-customized-rhel-system-image#composer-output-formats_composer-description describes that one can create RHEL Live ISOs using Image Builder.

> You can use Image Builder to create customized system images of Red Hat Enterprise Linux (...) through a command line interface in the `composer-cli` tool, or a graphical user interface in the RHEL 8 web console. 

Is it described somewhere how to produce a RHEL 8 Workstation Live ISO using the `composer-cli` tool?

**Comment by bcl** [comment]
Anything in CentOS is the same as what's in the rhel8-branch, which will have the most updated code so there's no need for a centos branch.
You can create the iso using livemedia-creator or lorax-composer, which is an API on top of livemedia-creator.

Also note that the live iso created with lorax-composer isn't the same as the Fedora live iso, it is basically just an iso wrapper around a disk image and doesn't contain all the extra hacks that are in the *-livemedia.ks examples.

The reason why there aren't examples for RHEL in the same repo is that you need to run the version of livemedia-creator that is included in the release you are building for.

**Comment by probonopd** [comment]
> you need to run the version of livemedia-creator that is included in the release you are building for

Thanks, I will try to go that route then.

**Comment by probonopd** [comment]
Do you know in which package `livemedia-creator` is hiding on the RHEL 8 DVD? I can't seem to find it.

**Comment by bcl** [comment]
It is part of lorax.

**Comment by probonopd** [comment]
...which seems to be part of AppStream rather than BaseOS and hence not on the DVD.
(Just for future reference in case someone is wondering the same thing, namely where to find it.)

**Comment by probonopd** [comment]
Now I am booted into CentOS 8, and have `dd`'d the CentOS 8 DVD on a USB stick that is `/dev/sdb` (the same stick that I used to install CentOS 8 to a dedicated SSD).

```
[root@localhost user]# livemedia-creator --make-iso --ks /usr/share/doc/lorax/rhel-livemedia.ks --iso=/dev/sdb
2019-10-13 09:21:40,187: livemedia-creator v28.14.23-1
2019-10-13 09:21:40,188: selinux is enabled and in Enforcing mode
2019-10-13 09:21:40,305: disk_img = /var/tmp/lmc-disk-78n3cn1b.img
2019-10-13 09:21:40,305: Using disk size of 6658MiB
2019-10-13 09:21:40,306: install_log = /home/user/virt-install.log
2019-10-13 09:21:41,389: qemu vnc=127.0.0.1:0
2019-10-13 09:21:41,389: Running qemu
2019-10-13 09:21:41,426: Processing logs from ('127.0.0.1', 53176)
2019-10-13 09:23:41,570: Installation error detected. See logfile for details.
2019-10-13 09:23:41,570: VirtualInstall failed: QEMUInstall failed
2019-10-13 09:23:41,571: unmounting the iso
2019-10-13 09:23:41,605: Install failed: QEMUInstall failed
2019-10-13 09:23:41,606: Removing bad disk image
2019-10-13 09:23:41,606: ERROR: Image creation failed: QEMUInstall failed
2019-10-13 09:23:41,606: Image creation failed: QEMUInstall failed
```

[program.log](https://github.com/weldr/lorax/files/3721773/program.log)

[virt-install.log](https://github.com/weldr/lorax/files/3721771/virt-install.log)

[livemedia.log](https://github.com/weldr/lorax/files/3721772/livemedia.log)

I also have saved the ISO to a NTFS drive, but unlike other distributions CentOS 8 is unable to mount NTFS drives out of the box.

Unbelievable that in 2019 you still have to fiddle around, i.e.,

```
[root@localhost user]# yum install epel-release
[root@localhost user]# yum install ntfs-3g
Last metadata expiration check: 0:00:12 ago on Sun Oct 13 09:28:32 2019.
No match for argument: ntfs-3g
Error: Unable to find a match
```

Even more unbelievable that even then it does not work. Other distributions just do this out of the box.

So let's try with

```
[root@localhost user]# livemedia-creator --make-iso --ks /usr/share/doc/lorax/rhel-livemedia.ks --iso=/dev/sdb --no-virt
```

even though running with `--no-virt` is not recommended.

Getting

```
[root@localhost user]# livemedia-creator --make-iso --ks /usr/share/doc/lorax/rhel-livemedia.ks --iso=/dev/sdb --no-virt
2019-10-13 09:30:52,263: livemedia-creator v28.14.23-1
2019-10-13 09:30:52,263: selinux is enabled and in Enforcing mode
2019-10-13 09:30:52,382: disk_img = /var/tmp/lmc-disk-8ixmhebi.img
2019-10-13 09:30:52,382: Using disk size of 6658MiB
2019-10-13 09:30:55,179: Running anaconda.
2019-10-13 09:31:04,221: Starting installer, one moment...
2019-10-13 09:31:04,221: terminal size detection failed, using default width
2019-10-13 09:31:04,221: anaconda 29.19.0.40-1.el8 for Linux 8 (pre-release) started.
2019-10-13 09:31:04,221: 09:31:04 Not asking for VNC because of an automated install
2019-10-13 09:31:04,659: Processing logs from ('127.0.0.1', 54648)
2019-10-13 09:31:38,897: Starting automated install.................................No protocol specified
2019-10-13 09:31:38,898: Unable to init server: Could not connect: Connection refused
2019-10-13 09:31:38,947: No protocol specified
2019-10-13 09:31:38,947: Unable to init server: Could not connect: Connection refused
2019-10-13 09:31:38,947: No protocol specified
2019-10-13 09:31:38,947: Unable to init server: Could not connect: Connection refused
2019-10-13 09:34:40,231: Error in atexit._run_exitfuncs:
2019-10-13 09:34:40,240: Traceback (most recent call last):
2019-10-13 09:34:40,240: File "/usr/lib/python3.6/site-packages/blivet/threads.py", line 53, in run_with_lock
2019-10-13 09:34:40,240: return m(*args, **kwargs)
2019-10-13 09:34:40,240: File "/usr/lib64/python3.6/site-packages/pyanaconda/storage/osinstall.py", line 2062, in umount_filesystems
2019-10-13 09:34:40,240: self.fsset.umount_filesystems(swapoff=swapoff)
2019-10-13 09:34:40,241: File "/usr/lib64/python3.6/site-packages/pyanaconda/storage/osinstall.py", line 775, in umount_filesystems
2019-10-13 09:34:40,241: device.format.teardown()
2019-10-13 09:34:40,241: File "/usr/lib/python3.6/site-packages/blivet/threads.py", line 53, in run_with_lock
2019-10-13 09:34:40,241: return m(*args, **kwargs)
2019-10-13 09:34:40,241: File "/usr/lib/python3.6/site-packages/blivet/formats/__init__.py", line 649, in teardown
2019-10-13 09:34:40,241: self._teardown(**kwargs)
2019-10-13 09:34:40,241: File "/usr/lib/python3.6/site-packages/blivet/threads.py", line 53, in run_with_lock
2019-10-13 09:34:40,241: return m(*args, **kwargs)
2019-10-13 09:34:40,241: File "/usr/lib/python3.6/site-packages/blivet/formats/fs.py", line 611, in _teardown
2019-10-13 09:34:40,241: raise FSError("umount of %s failed (%d)" % (mountpoint, rc))
2019-10-13 09:34:40,242: blivet.errors.FSError: umount of /run/user/1000 failed (32)
2019-10-13 09:34:40,242: 
2019-10-13 09:34:40,242: ================================================================================
2019-10-13 09:34:40,242: ================================================================================
2019-10-13 09:34:40,242: Installation
2019-10-13 09:34:40,242: 
2019-10-13 09:34:40,242: 1) [x] Language settings                 2) [x] Time settings
2019-10-13 09:34:40,242: (English (United States))                (US/Eastern timezone)
2019-10-13 09:34:40,242: 3) [!] Installation source               4) [!] Software selection
2019-10-13 09:34:40,242: (Error setting up software               (Error checking software
2019-10-13 09:34:40,243: source)                                  selection)
2019-10-13 09:34:40,243: 5) [x] Network configuration             6) [ ] User creation
2019-10-13 09:34:40,243: (Wired (enp0s25) connected)              (No user will be created)
2019-10-13 09:34:40,243: 
2019-10-13 09:34:40,243: 
2019-10-13 09:34:40,243: The installation was stopped due to an error which occurred while running in non-interactive cmdline mode. Since there cannot be any questions in cmdline mode, edit your kickstart file and retry installation.
2019-10-13 09:34:40,243: The exact error message is:
2019-10-13 09:34:40,243: 
2019-10-13 09:34:40,243: The following mandatory spokes are not completed:
2019-10-13 09:34:40,243: Installation source
2019-10-13 09:34:40,244: Software selection.
2019-10-13 09:34:40,244: 
2019-10-13 09:34:40,244: The installer will now terminate.
2019-10-13 09:34:40,571: Running anaconda failed: process '['anaconda', '--kickstart', '/usr/share/doc/lorax/rhel-livemedia.ks', '--cmdline', '--loglevel', 'debug', '--dirinstall', '--remotelog', '127.0.0.1:48677']' exited with status 1
2019-10-13 09:34:40,573: Shutting down log processing
2019-10-13 09:34:40,692: Install failed: novirt_install failed
2019-10-13 09:34:40,693: Removing bad disk image
2019-10-13 09:34:40,701: ERROR: Image creation failed: novirt_install failed
2019-10-13 09:34:40,709: Image creation failed: novirt_install failed
```

[program.log](https://github.com/weldr/lorax/files/3721790/program.log)
[livemedia.log](https://github.com/weldr/lorax/files/3721791/livemedia.log)

I am lost, any help appreciated.

**Comment by probonopd** [comment]
This is what I mean by "having to fiddle around", things don't work, you search around, you find new information, then maybe it works maybe it doesn't. Rather than there being clear instructions that work right on the first try.

Trying now:

```
[root@localhost user]# dnf config-manager --enable epel-playground
[root@localhost user]# yum install ntfs-3g
[root@localhost user]# mount /dev/sdcX1 /mnt
[root@localhost user]# livemedia-creator --make-iso --ks /usr/share/doc/lorax/rhel-livemedia.ks --iso=/mnt/Linux_Software/Linux\ Distros/CentOS-8-x86_64-1905-dvd1.iso --no-virt
```

**Comment by probonopd** [comment]
Maybe an update helps and whatever came with the RHEL 8 ISO is already outdated?

```
[user@localhost ~]$ sudo yum install anaconda lorax
(...)
  anaconda-core-29.19.0.43-1.el8_0.x86_64                                       
  anaconda-gui-29.19.0.43-1.el8_0.x86_64                                        
  anaconda-tui-29.19.0.43-1.el8_0.x86_64                                        
  anaconda-widgets-29.19.0.43-1.el8_0.x86_64                                    
  blivet-data-1:3.1.0-12.el8_0.noarch                                           
  python3-blivet-1:3.1.0-12.el8_0.noarch    
```

This time:

```
[root@localhost user]# livemedia-creator --make-iso --ks /usr/share/doc/lorax/rhel-livemedia.ks --iso=/mnt/Linux_Software/Linux\ Distros/CentOS-8-x86_64-1905-dvd1.iso
2019-10-13 09:58:23,076: livemedia-creator v28.14.23-1
2019-10-13 09:58:23,077: selinux is enabled and in Permissive mode
2019-10-13 09:58:23,189: disk_img = /var/tmp/lmc-disk-4uh7dwy7.img
2019-10-13 09:58:23,189: Using disk size of 6658MiB
2019-10-13 09:58:23,190: install_log = /home/user/virt-install.log
2019-10-13 09:58:23,413: qemu vnc=127.0.0.1:0
2019-10-13 09:58:23,414: Running qemu
2019-10-13 09:58:23,459: Processing logs from ('127.0.0.1', 33924)
2019-10-13 10:01:17,639: Installation error detected. See logfile for details.
2019-10-13 10:01:17,639: VirtualInstall failed: QEMUInstall failed
2019-10-13 10:01:17,639: unmounting the iso
2019-10-13 10:01:17,716: Install failed: QEMUInstall failed
2019-10-13 10:01:17,716: Removing bad disk image
2019-10-13 10:01:17,716: ERROR: Image creation failed: QEMUInstall failed
2019-10-13 10:01:17,717: Image creation failed: QEMUInstall failed
```

> See logfile for details.

Which logfile? Let me attach them all:

```
[root@localhost user]# mkdir -p logs && find . -type f -maxdepth 2 -name '*.log' -exec cp {} logs/ \; 
```

[logs.zip](https://github.com/weldr/lorax/files/3721830/logs.zip)

**Comment by probonopd** [comment]
This seems to go a little bit further:

```
[user@localhost ~]$ git clone https://github.com/alphacc/eight-livecd
[user@localhost ~]$ cd eight-livecd/
[user@localhost eight-livecd]$ sudo setenforce 0
[user@localhost eight-livecd]$ sudo livemedia-creator --ks ks/el8-livemedia-minimal.ks --no-virt --resultdir media/el8 --project RHEL-8-live --make-iso --iso-only --iso-name RHEL-8-live-x86_64.iso --releasever 8 --volid RHEL-8-live --title RHEL-live --macboot
```

But I want to do without the third-party https://github.com/alphacc/eight-livecd.

**Comment by bcl** [comment]
github issues really aren't the best for these kinds of problems. The mailing list and bugzilla (for attaching logs) is better. It looks like you have things working now, but here are a few observations:

* Forget NTFS, don't try to complicate things when you are first trying to get them working.
* --iso should point to the boot.iso file, not to a drive. A drive *may* work, but I do not test that.
* --no-virt does not use --iso, it uses the anaconda installed on the host so you can drop it.
* If the anaconda log is saying the Installation Source spoke is incomplete that means your url and repo lines in the kickstart are wrong, or there is a network problem.
* This should all be working with SELinux in Enforcing, but when debugging issues it doesn't hurt to set it to Permissive until you have a working process.

You can ignore the 'Unable to init server ...' and 'Gtk cannot be initialized' errors, they are side effects of other errors.

And yes, the CentOS 8 release lags behind RHEL 8, but it should be working.

**Comment by zfred68** [comment]
the "Unable to init server", it is very easy to overlook that you indeed have network working within your build (chroot or mock or other) environment.  test a wget or ping command, check your /etc/resolv.conf
